/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JogoDeCorrida;

public class App {

    public static void main(String[] args){
        Veiculo fusca = new Veiculo(new Motor_Fusca());
        Veiculo ferrari = new Veiculo(new Motor_Ferrari());
        Veiculo lamborguini = new Veiculo(new Motor_Lamborguini());
        
        System.out.println(fusca.acelerar());
        System.out.println(ferrari.acelerar());
        System.out.println(lamborguini.acelerar());
    }
}
